/**
 * serverless-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CivDef } from './civDef';
import { DLC } from './dLC';
import { GameSpeed } from './gameSpeed';
import { MapSize } from './mapSize';
import { PlatformSaveLocation } from './platformSaveLocation';


export interface CivGame { 
    id: string;
    displayName: string;
    turnTimerSupported: boolean;
    assetPrefix: string;
    leaders: Array<CivDef>;
    dlcs: Array<DLC>;
    gameSpeeds: Array<GameSpeed>;
    mapSizes: Array<MapSize>;
    maps: Array<any>;
    saveLocations: { [key: string]: PlatformSaveLocation; };
    dataPaths: { [key: string]: string; };
    savePath: string;
    saveExtension: string;
    runUrls: { [key: string]: string; };
}
