/**
 * serverless-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WebPushSubscription } from './webPushSubscription';


export interface PrivateUserData { 
    steamId: string;
    websocketConnectionIds?: Array<string>;
    emailAddress?: string;
    newTurnEmails?: boolean;
    webhookUrl?: string;
    webPushSubscriptions?: Array<WebPushSubscription>;
    newGameEmails?: boolean;
    newGameEmailsWithPasswords?: boolean;
    newGameEmailTypes?: Array<string>;
    newGameEmailFilter?: string;
}
