/**
 * serverless-api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RecordNumberNumber_ } from './recordNumberNumber_';


export interface TurnData { 
    firstTurnEndDate?: Date;
    lastTurnEndDate?: Date;
    turnsPlayed: number;
    turnsSkipped: number;
    timeTaken: number;
    fastTurns: number;
    slowTurns: number;
    hourOfDayQueue: string;
    dayOfWeekQueue: string;
    turnLengthBuckets: RecordNumberNumber_;
    yearBuckets: RecordNumberNumber_;
}
